/*
------------------------------------------------------------
Module Name : signExtend

Description :
- Extracts the immediate field from the 32-bit instruction.
- Supports different immediate formats based on the instruction type
  (I-Type, S-Type and B-Type).
- Performs sign extension to convert the extracted immediate into a
  32-bit signed value.
- The immediate extraction mode is selected using the ImmSrc control signal
  generated by the Main Decoder.
------------------------------------------------------------
*/

module signExtend #(
    parameter INSTR_WIDTH  = 32,
    parameter IMM_WIDTH    = 32
) (
    input       wire     [INSTR_WIDTH - 1:7]     Instr,  // 32-bit instruction
    input       wire          [1:0]              ImmSrc, // Immediate source selector
    output      reg       [IMM_WIDTH - 1:0]      ImmExt  // 32-bit sign-extended immediate
);

always @(*) begin

    case(ImmSrc)
        2'b00: ImmExt = {{20{Instr[31]}}, Instr[31:20]}; // I-Type & Load Instructions
        2'b01: ImmExt = {{20{Instr[31]}}, Instr[31:25], Instr[11:7]}; // S-Type
        2'b10: ImmExt = {
                    {19{Instr[31]}},
                    Instr[31],
                    Instr[7],
                    Instr[30:25],
                    Instr[11:8],
                    1'b0
                }; // B-Type
        default: ImmExt = {IMM_WIDTH{1'b0}}; // Default case
    endcase
    
end

endmodule